### ISSUE TITLE
vPRO - Folder upload doesn't work

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#199]
Fairdrop PRO Version 0.5.0 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
related to #189

It is only upload one file from the selected folder.

**Comment by GasperX93** [comment]
Fairdrop PRO Version 0.5.1 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

Hey @significance,

Some strange stuff going on with folder/multi-files upload.

1. When sending the file I can't select the whole folder, but I can select more files.
2. I selected 4 files but on the confirmation screen, it is shown that I selected 11 files.
3. Instead of file I sent, the recipient got the file I sent it previously.
4. I don't have files that I sent in Sent folder.

The record:
https://swarm.fairdrop.pro:/bzz-list:/4e88e86085db7e302d68d84df2f8ecf8057b63c9ff6750828bd271d21d15de6c/

**Comment by crtahlin** [comment]
@plur9 & @significance 
It would be beneficial if you put short comments when closing/opening. I guess you guys know what is happening, but for any 3rd party I'm assuming that @significance has closed due to a fix, and that @plur9 has reopened, since it still does not work. 
In this context it would also be beneficial, if after the fix @significance would list where the fix is deployed, so that @GasperX93 could test and confirm and then possibly close.
While @plur9 could also list where he tested, that does not work and would expect it to (maybe it is not even deployed there yet).

**Comment by plur9** [comment]
My mistake! Sorry!!!!
